name: Markdown to RFC
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

env:
  BASE_FILE_NAME: draft-timbru-sidrops-vrp-notation-00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: cache xml2rfc cache
        id: xml2rfc-cache
        uses: actions/cache@v2
        with:
          key: xml2rfc-cache
          path: .cache-xml2rfc

      - name: create output dir
        run: |
          mkdir output

      - name: build XML
        uses: addnab/docker-run-action@v3
        with:
          image: paulej/rfctools
          options: -v ${{ github.workspace }}:/rfc -v ${{ github.workspace }}/.cache-xml2rfc:/var/cache/xml2rfc -w /rfc
          run: |
            mmark ${BASE_FILE_NAME}.md > output/${BASE_FILE_NAME}.xml

      - name: build html
        uses: addnab/docker-run-action@v3
        with:
          image: paulej/rfctools
          options: -v ${{ github.workspace }}:/rfc -v ${{ github.workspace }}/.cache-xml2rfc:/var/cache/xml2rfc -w /rfc
          run: |
            xml2rfc -p output --text --html output/${BASE_FILE_NAME}.xml

      - name: Archive output
        uses: actions/upload-artifact@v2
        with:
          name: xml2rfc-output
          path: output/
