name: Markdown to RFC
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: cache xml2rfc cache
        id: xml2rfc-cache
        uses: actions/cache@v3
        with:
          key: xml2rfc-cache
          path: .cache-xml2rfc

      - name: create output dir
        run: |
          mkdir output

      - name: build XML
        uses: addnab/docker-run-action@v3
        with:
          image: paulej/rfctools
          options: -v ${{ github.workspace }}:/rfc -v ${{ github.workspace }}/.cache-xml2rfc:/var/cache/xml2rfc -w /rfc
          run: |
            mmark draft-sidrops-vrp-notation-00.md > output/draft-sidrops-vrp-notation-00.xml

      - name: build html
        uses: addnab/docker-run-action@v3
        with:
          image: paulej/rfctools
          options: -v ${{ github.workspace }}:/rfc -v ${{ github.workspace }}/.cache-xml2rfc:/var/cache/xml2rfc -w /rfc
          run: |
            xml2rfc -p output --text --html output/draft-sidrops-vrp-notation-00.xml

      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          name: xml2rfc-output
          path: output/
